ansible_python_interpreter: /usr/bin/python3.12
server_timezone: "Europe/Moscow"
server_hostname: "growerhub"

app_user: watering-admin
app_dir: /home/watering-admin/growerhub/server
venv_dir: /home/watering-admin/growerhub/server/.venv
# ВАЖНО: предполагаю, что в run.py есть объект FastAPI с именем "app"
app_module: "run:app"
app_port: 8000
app_workers: 2
app_env_file: /etc/growerhub.env
python_cmd: /usr/bin/python3

# TODO: perenesti parol' iz gh_db_url v zashchishchennoye mesto
gh_db_url: "postgresql://db-admin:gh_db_admin_dev_1234@192.168.0.81:5432/gh_db"
