# Переменные для сервера gh-db (192.168.0.81)
postgresql_version: 16
postgresql_conf_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_conf_path: "{{ postgresql_conf_dir }}/postgresql.conf"
pg_hba_conf_path: "{{ postgresql_conf_dir }}/pg_hba.conf"

# Основные параметры базы данных
gh_db_name: "gh_db"
gh_db_admin_user: "db-admin"
# postgresql_conf_path: "/etc/postgresql/16/main/postgresql.conf"
# postgresql_hba_path: "/etc/postgresql/16/main/pg_hba.conf"
# TODO: перенести пароль gh_db_admin_password в защищённое хранилище
gh_db_admin_password: "ЗАГЛУШКА_СЮДА_ПАРОЛЬ_ПОТОМ_ПОМЕНЯЕМ"

gh_db_timezone: "Europe/Moscow"

gh_db_trusted_clients:
  - "192.168.0.11/32"
  - "192.168.0.85/32"
